import = ["~/.config/alacritty/alacritty-theme/themes/solarized_dark.toml"]

[cursor.style]
shape = "Block"

[font]
size = 14.0

[font.normal]
# family = "Hack Nerd Font Mono"
family = "MonaspiceNe Nerd Font Mono"

[font.bold]
# family = "Hack Nerd Font Mono"
family = "MonaspiceKr Nerd Font Mono"

[font.italic]
# family = "Hack Nerd Font Mono"
family = "MonaspiceRn Nerd Font Mono"

[window]
blur = true
decorations = "transparent"
dynamic_padding = false
opacity = 0.8

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 16
y = 28
